spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  project:
    name: equity-positions
  application:
    name: equity-positions

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true

mybatis:
  mapperLocations:
    - classpath*:/mapper/*.xml
    - classpath*:/mapper/*/*Mapper.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true

# 日志 logbak
logging:
  config: classpath:logback-spring.xml
